Fix #520 "fix documentation for bin and extraLibs options"
QuasarApp/CQtDeployer pull request #521
Opened 2021-02-06 16:38 UTC by EndrII

2021-02-07 03:06 UTC, pzhlkj6612 commented
I'm rewriting the instruction about the option "-bin". Please wait.

2021-02-07 08:35 UTC, EndrII commented
@pzhlkj6612 okay, create pull request into the  task_520 branch and checkout from it.

2021-02-22 09:09 UTC, EndrII commented
@pzhlkj6612 
Do you will make any changes to this PR?. If not, please do a review.

2021-02-22 14:42 UTC, EndrII commented on docs/en/Options.md
> +|                             |names contain mySql to the project folder. This option is case sensitive. This option will not copy libraries whose names are not mentioned in the list of dependencies
yes you right.

2021-02-22 14:50 UTC, EndrII commented on docs/en/Options.md
> +|   -bin [list,params]       | Deployable file or folder. For example -bin ~/my/project/bin/,~/my/project/bin.exe. The bin option can also work with files of any format. Everything that will be liste
1. ok i will add description for the deployable files.
2. no, the Distribution Kit have a strong structure, all files marked like bin must be copied in to binOut folder.
3. Yes, you right.

2021-02-22 15:24 UTC, pzhlkj6612 commented on docs/en/Options.md
> +|   -bin [list,params]       | Deployable file or folder. For example -bin ~/my/project/bin/,~/my/project/bin.exe. The bin option can also work with files of any format. Everything that will be liste
> no, the Distribution Kit have a strong structure, all files marked like bin must be copied in to binOut folder.

Well, what if the user use the parameter `targetDir`?

2021-02-22 15:27 UTC, EndrII commented on docs/en/Options.md
> +|   -bin [list,params]       | Deployable file or folder. For example -bin ~/my/project/bin/,~/my/project/bin.exe. The bin option can also work with files of any format. Everything that will be liste
targetDir sets root for your distribution and XXXoutDir options sets releastive path from root.
example 
targetDir = /opt/MyApp
binDir = targetDir + binPutDir = /opt/MyApp/bin

2021-02-22 15:48 UTC, pzhlkj6612 commented on docs/en/Options.md
> +|   -bin [list,params]       | Deployable file or folder. For example -bin ~/my/project/bin/,~/my/project/bin.exe. The bin option can also work with files of any format. Everything that will be liste
I don't think we should assume that the option "binOutDir" exists by default.

<br>

And,

> Why "DestributionKit/bin"? It is better to use "the destination directory".

I mean that we should not use the hardcoded name "DestributionKit". This name did not exist in Option.md before the modification, right?

2021-02-22 15:51 UTC, EndrII commented on docs/en/Options.md
> +|   -bin [list,params]       | Deployable file or folder. For example -bin ~/my/project/bin/,~/my/project/bin.exe. The bin option can also work with files of any format. Everything that will be liste
oh i understand you, yes i will remove this hard code from docs.

2021-02-23 14:04 UTC, EndrII commented on docs/en/Options.md
> +
```suggestion
## Definitions in description 
**System environment** - is  pathes of the sstem libraryes.
    Windows: C:\Windows\System32 and C:\Windows\SysWOW64. And any another pathes difined in the PATH variable.
    Linux: /usr/lib and /lib. And any another pathes defined in the LD_LIBRARY_PATH or PATH variables.

**deployable files** - are all file that will be copied into distribution (incude executable files)

**Targets** - are all executable files marked by bin option.
**Executable files ** - are all files with PE, ELF and Mach-O formats.

```

2021-02-23 14:05 UTC, pzhlkj6612 requested changes

2021-02-23 14:11 UTC, EndrII commented on Deploy/deploycore.cpp
> +                 " The CQtDeployer will be search dependencies in a system environment and in libDir paths."},
```suggestion
                 " For folders:"
                 " CCQtDeployer will enter these folders and non-recursively copy all executable files to the destination directory."
                 " Then, CQtDeployer will extract all dependencies of the copied files and search dependencies in system environments and libDir paths."},
```

2021-02-23 14:12 UTC, EndrII commented on docs/en/Options.md
> +|   -bin [list,params]       | Files to deploy or folders that contain files to deploy. For example -bin ~/my/project/bin/,~/my/project/bin.exe,~/my/project/runtimeLinking/lib.dll. For files: These f
i am merge it

2021-02-23 14:12 UTC, pzhlkj6612 commented on Deploy/deploycore.cpp
> +                 " The CQtDeployer will be search dependencies in a system environment and in libDir paths."},
Oh I forgot this.

2021-02-23 14:15 UTC, EndrII commented on docs/en/Options.md
> +
@pzhlkj6612 What do you think about this ?

2021-02-23 15:20 UTC, EndrII commented on docs/ru/Options.md
> +
```suggestion
## Определения в описании
**Системное окружение** - пути к системным библиотекам.
  * Windows:
    * Пути, определенные в переменной PATH.
    * C:\Windows\System32
    * C:\Windows\SysWOW64
  * Linux:
    * Пути, определенные в переменных LD_LIBRARY_PATH и PATH.
    * /usr/lib
    * /lib
**Развертываемые файлы** - это все файлы, которые будут скопированы в дистрибутив (включая исполняемые файлы)
**Цели** - это все исполняемые файлы, отмеченные опцией bin.
**Исполняемые файлы** - это все файлы в форматах PE, ELF и Mach-O.
```

2021-02-24 00:07 UTC, pzhlkj6612 requested changes

2021-02-24 13:27 UTC, pzhlkj6612 approved these changes
The documentation for `bin` and `extraLibs` options in this PR looks good to me, so merge it.

2021-02-24 13:28 UTC, merged