Update guide
QuasarApp/CQtDeployer pull request #537
Opened 2021-02-22 09:46 UTC by EndrII

Added example into guide.

2021-02-22 11:27 UTC, Oleg-designer commented
> ### Deploy yor executable file.

2021-02-22 12:17 UTC, Oleg-designer commented
English version fix
> Deploy yor executable file.

Change "yor" to "your" please 

Russian version fix

> ваш исполняемый файл будет находитья на уровень выше

Change "находитья" to "находиться"

> После установки буду созданы все небходимые ярлыки.

Change "небходимые" to "необходимые"

> используються

Change to "используются"

2021-02-22 12:22 UTC, Oleg-designer reviewed
English version fix

> Deploy yor executable file.

Change "yor" to "your" please

Russian version fix

> ваш исполняемый файл будет находитья на уровень выше

Change "находитья" to "находиться"

> После установки буду созданы все небходимые ярлыки

Change "небходимые" to "необходимые"

> используються

Change to "используются"

2021-02-22 13:43 UTC, EndrII commented
@Oleg-designer i am fixed all typo mistakes. Make review again please.

2021-02-22 13:49 UTC, Oleg-designer approved these changes
All is fine

2021-02-22 14:53 UTC, merged

2021-02-22 15:13 UTC, pzhlkj6612 requested changes

2021-02-22 15:13 UTC, pzhlkj6612 commented on docs/en/Guide.md
> +The **recursiveDepth** parameters are used to set the search depth for libDir and qmlDir.
```suggestion
The **libDir** parameter is used to set the paths to the directory paths contain dependencies of your application, and the **qmlDir** parameter is used to set the directory paths contain the qml files required by your application. In this example, the application source code root is selected by these two options.

The **recursiveDepth** parameter is used to set the search depth of **libDir** and **qmlDir**. 
```

Each parameter itself is singular, not plural.

2021-02-22 15:13 UTC, pzhlkj6612 commented on docs/en/Guide.md
> +6. Start the build.
```suggestion
6. Start the building
```

2021-02-22 15:14 UTC, pzhlkj6612 commented
Oh, it has been merged... Awkward.

2021-02-22 15:16 UTC, EndrII commented
@pzhlkj6612 thanks, i am open new PR with you fixes.

2021-02-22 15:22 UTC, pzhlkj6612 commented
It's ok.

2021-02-23 06:44 UTC, pzhlkj6612 commented
Changes I requested have been made in #538 .