Fixes after updating of the guide.
QuasarApp/CQtDeployer pull request #538
Opened 2021-02-22 15:48 UTC by EndrII

This PR contains fixes after last review in the #537 PR

2021-02-22 15:55 UTC, pzhlkj6612 requested changes
The period (.) at the end of the ordered list item is inconsistent.

2021-02-22 15:55 UTC, pzhlkj6612 commented on docs/en/Guide.md
> +    1. Run qmake with the -r option for release build.
```suggestion
    1. Run qmake with the -r option for release build
```

2021-02-22 15:55 UTC, pzhlkj6612 commented on docs/en/Guide.md
> +3. Choose a release build.
```suggestion
3. Choose a release build
```

2021-02-22 15:55 UTC, pzhlkj6612 commented on docs/en/Guide.md
> +6. Start the building.
```suggestion
6. Start the building
```

2021-02-23 05:43 UTC, EndrII commented
@pzhlkj6612 done

2021-02-23 06:42 UTC, pzhlkj6612 approved these changes
OK.

2021-02-23 06:42 UTC, merged