Fix icon option
QuasarApp/CQtDeployer pull request #593
Opened 2021-05-12 13:51 UTC by EndrII

This changes  fix an icon option for multi targets distributions.

2021-05-13 09:33 UTC, pzhlkj6612 commented
Hi. As there is no related issue or detailed commit message, I want to know what this PR does. That is, what is the difference between the behavior of CQtDeployer before and after this PR?

2021-05-13 13:46 UTC, EndrII commented
There is a bug due to which the icon is not copyed in a multi-package distribution. At the moment, the error has not been fixed and it is not known where it is. But it reproduces with about a 10% chance.

In this pull request, I found the expected location where it could be and fixed the problem, but as it turned out, this is not the only place where the error occurs.

2021-05-14 12:50 UTC, pzhlkj6612 requested changes

2021-05-14 12:50 UTC, pzhlkj6612 commented on Deploy/configparser.cpp
> +                                                " but the %1 not inited!").
```suggestion
            QuasarAppUtils::Params::log(QString("The target %0 belongs to package %1"
                                                " but this package is not initialized!").
```

2021-05-14 12:51 UTC, EndrII commented on Deploy/configparser.cpp
> +                                                " but the %1 not inited!").
thanks

2021-05-17 14:13 UTC, merged