[WIP] Documentation correction
QuasarApp/CQtDeployer pull request #616
Opened 2021-05-25 07:10 UTC by Oleg-designer

ref #560

2021-05-25 10:02 UTC, pzhlkj6612 commented
Hi.

The indentation changes in 269153227c6f0229f0dd1723d54312febaf9ad6d doesn't seem to make much sense. What's your purpose about it?

2021-05-25 11:28 UTC, Oleg-designer commented
> Hi.
> 
> The indentation changes in [2691532](https://github.com/QuasarApp/CQtDeployer/commit/269153227c6f0229f0dd1723d54312febaf9ad6d) doesn't seem to make much sense. What's your purpose about it?

Hi, i am doing small fixes for doxygen documentation. Yes,  2691532 there is no point in making these changes, it's just for testing.

2021-06-09 08:08 UTC, pzhlkj6612 reviewed
In /md/en/Guide.md , there are many modifications about removing a path delimiter from a file path. For example:

```diff
- /home/andrei/Qt/5.15.2/gcc_64/qml/QtQml/WorkerScript.2/plugins.qmltypes
+ /home/andrei/Qt/5.15.2/gcc_64/qml/QtQmlWorkerScript.2/plugins.qmltypes
```

Is it on purpose?

2021-06-09 08:11 UTC, EndrII requested changes

2021-06-09 08:11 UTC, EndrII commented on md/en/Guide.md
> +    Info: copy :/home/andrei/Qt/5.15.2/gcc_64/qml/QtQuick.2plugins.qmltypes
you remove '/' from paths. please revert this changes.

2021-06-09 08:13 UTC, EndrII commented
> In /md/en/Guide.md , there are many modifications about removing a path delimiter from a file path. For example:
> 
> ```diff
> - /home/andrei/Qt/5.15.2/gcc_64/qml/QtQml/WorkerScript.2/plugins.qmltypes
> + /home/andrei/Qt/5.15.2/gcc_64/qml/QtQmlWorkerScript.2/plugins.qmltypes
> ```
> 
> Is it on purpose?

i think it is typo mistake.

2021-06-09 08:31 UTC, EndrII approved these changes
looks good for me.

2021-06-09 09:10 UTC, merged