Fix patrons list
QuasarApp/CQtDeployer pull request #686
Opened 2022-02-08 07:15 UTC by EndrII

Fix of the patrons list.

2022-02-08 10:07 UTC, EndrII commented
@kartaris  please review this pull request

2022-02-08 10:54 UTC, kartaris requested changes
GETFLOW.TECH

2022-02-09 06:39 UTC, EndrII commented
@kartaris please review this pull request.

2022-02-09 07:15 UTC, kartaris approved these changes

2022-02-09 07:16 UTC, merged